### ISSUE TITLE
Undefined dimen

### ISSUE THREAD

**Issue by sytolk** [andrebts/login-basics#4]
``` xml
<dimen name="nav_header_vertical_spacing">16dp</dimen>
```

You forgot to define this in res/values/dimens.xml
and for devices with API < 21 its have after login

```
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x1
            at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
            at android.view.View.<init>(View.java:3345)
            at android.widget.TextView.<init>(TextView.java:447)
            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:48)
            at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
            at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
            at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:912)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:966)
            at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:207)
            at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:246)
            at android.support.design.widget.NavigationView.<init>(NavigationView.java:168)
            at android.support.design.widget.NavigationView.<init>(NavigationView.java:92)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:255)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at bscorp.appbase.MainActivity.onCreate(MainActivity.java:22)
```

**Comment by andrebts** [comment]
Solved by commit 9739857.
